name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Download dependencies
      run: make deps
    
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    - name: Run linter
      run: make lint
    
    - name: Run tests
      run: make test
    
    - name: Run tests with race detection
      run: make test-race
    
